import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'dart:html' as html;
import 'login_page.dart';
import 'signup_page.dart';
import 'doctor_dashboard.dart';
import 'patient/patient_dashboard.dart';
import 'admin/admin_dashboard.dart';
import 'auth_action_handler.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Load environment variables from a local .env file if present. This is
  // optional — if the file doesn't exist or doesn't define OPENAI_API_KEY,
  // dotenv.env['OPENAI_API_KEY'] will be null and the app will use the
  // built-in rule-based chatbot.
  try {
    await dotenv.load(fileName: '.env');
    print('DEBUG MAIN: .env loaded successfully');
    print(
      'DEBUG MAIN: GEMINI_API_KEY present: ${dotenv.env['GEMINI_API_KEY']?.isNotEmpty ?? false}',
    );
    if (dotenv.env['GEMINI_API_KEY']?.isNotEmpty ?? false) {
      print(
        'DEBUG MAIN: GEMINI_API_KEY value starts with: ${dotenv.env['GEMINI_API_KEY']!.substring(0, 10)}...',
      );
    }
  } catch (e) {
    print('DEBUG MAIN: Error loading .env: $e');
  }

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Check if we're on web and handling a Firebase auth action
    Widget initialRoute = const LoginPage();

    if (kIsWeb) {
      final uri = Uri.parse(html.window.location.href);
      final mode = uri.queryParameters['mode'];
      final oobCode = uri.queryParameters['oobCode'];

      // If URL has Firebase action parameters, show the handler
      if (mode != null && oobCode != null) {
        initialRoute = const AuthActionHandler();
      }
    }

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Hospital Management',
      theme: AppTheme.themeData,
      home: initialRoute,
      routes: {
        '/login': (context) => const LoginPage(),
        '/signup': (context) => const SignupPage(),
        '/doctor': (context) => const DoctorDashboard(),
        '/patient': (context) => const DashboardScreen(),
        '/admin': (context) => const AdminDashboard(),
        '/auth-action': (context) => const AuthActionHandler(),
      },
    );
  }
}
