/// Canonical list of medical specialties.
/// Used for dropdowns and normalization in signup and consultation pages.
const List<String> canonicalSpecialties = [
  'Cardiology',
  'Dermatology',
  'Endocrinology',
  'Gastroenterology',
  'Hematology',
  'Infectious Disease',
  'Nephrology',
  'Neurology',
  'Obstetrics and Gynecology',
  'Oncology',
  'Ophthalmology',
  'Orthopedics',
  'Pediatrics',
  'Psychiatry',
  'Pulmonology',
  'Radiology',
  'Rheumatology',
  'Surgery',
  'Urology',
  'Emergency Medicine',
  'Family Medicine',
  'Internal Medicine',
  'Pathology',
  'Anesthesiology',
  'Physical Medicine and Rehabilitation',
];
