// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52Klu49hAQ5gkK5sJh1buudOJRI614Nw',
    appId: '1:355926868031:web:86326b0cc45b995317788a',
    messagingSenderId: '355926868031',
    projectId: 'hospital-management-syst-75183',
    authDomain: 'hospital-management-syst-75183.firebaseapp.com',
    storageBucket: 'hospital-management-syst-75183.firebasestorage.app',
    measurementId: 'G-SRNKNY2RMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeZ3r8aHqNa76p3ZT3aSg7xvRgf9fg6zE',
    appId: '1:355926868031:android:f4d595f8acda33f617788a',
    messagingSenderId: '355926868031',
    projectId: 'hospital-management-syst-75183',
    storageBucket: 'hospital-management-syst-75183.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFY4ygOhfzuzYEMRdZcbo9AqXRG0onxcU',
    appId: '1:355926868031:ios:5825c1ae0a28d6f417788a',
    messagingSenderId: '355926868031',
    projectId: 'hospital-management-syst-75183',
    storageBucket: 'hospital-management-syst-75183.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFY4ygOhfzuzYEMRdZcbo9AqXRG0onxcU',
    appId: '1:355926868031:ios:5825c1ae0a28d6f417788a',
    messagingSenderId: '355926868031',
    projectId: 'hospital-management-syst-75183',
    storageBucket: 'hospital-management-syst-75183.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB52Klu49hAQ5gkK5sJh1buudOJRI614Nw',
    appId: '1:355926868031:web:8fe74597c4ffc82e17788a',
    messagingSenderId: '355926868031',
    projectId: 'hospital-management-syst-75183',
    authDomain: 'hospital-management-syst-75183.firebaseapp.com',
    storageBucket: 'hospital-management-syst-75183.firebasestorage.app',
    measurementId: 'G-MY092BFLQC',
  );

}