import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'login_page.dart';
import 'signup_page.dart';
import 'doctor_dashboard.dart';
import 'patient_dashboard.dart';
import 'firebase_options.dart'; // ✅ Generated by `flutterfire configure`

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Try Firebase initialization safely
  try {
    await Firebase.initializeApp(
     options: DefaultFirebaseOptions.currentPlatform,
    );
    runApp(const MyApp());
  } catch (e, stack) {
    // ✅ If Firebase fails, show the error on screen instead of a white page
    runApp(
      MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          body: Center(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(20),
              child: Text(
                "⚠️ Firebase Initialization Failed:\n\n$e\n\n$stack",
                style: const TextStyle(color: Colors.red),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Hospital Management',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),

      // ✅ First screen
      home: const LoginPage(),

      // ✅ Named routes for easy navigation
      routes: {
        '/login': (context) => const LoginPage(),
        '/signup': (context) => const SignupPage(),
        '/doctor': (context) => const DoctorDashboard(),
        '/patient': (context) => const PatientDashboard(),
      },
    );
  }
}
